# Generated by Django 3.2 on 2022-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggPrevAnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Agg_Prev_Ann',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('unite', models.TextField(blank=True, db_column='Unité', null=True)),
                ('ligne', models.TextField(blank=True, db_column='Ligne', null=True)),
                ('des', models.TextField(blank=True, db_column='Désignation', null=True)),
                ('client', models.TextField(blank=True, db_column='Client', null=True)),
                ('obj', models.BigIntegerField(blank=True, db_column='Objectif', null=True)),
                ('capacite_jour', models.BigIntegerField(blank=True, db_column='Capacité jour', null=True)),
                ('brute_jour', models.BigIntegerField(blank=True, db_column='Brute_jour', null=True)),
                ('conforme_jour', models.BigIntegerField(blank=True, db_column='Conforme_jour', null=True)),
                ('rebut_jour', models.BigIntegerField(blank=True, db_column='Rebut_jour', null=True)),
                ('taux_jour', models.BigIntegerField(blank=True, db_column='Taux_jour', null=True)),
                ('brute_mois', models.BigIntegerField(blank=True, db_column='Brute_mois', null=True)),
                ('conforme_mois', models.BigIntegerField(blank=True, db_column='Conforme_mois', null=True)),
                ('rebut_mois', models.BigIntegerField(blank=True, db_column='Rebut_mois', null=True)),
                ('taux_real', models.FloatField(blank=True, db_column='Taux_real', null=True)),
                ('taux_rebut', models.FloatField(blank=True, db_column='Taux_rebut', null=True)),
                ('pu_cout_revient', models.FloatField(blank=True, db_column='PU_cout_revient', null=True)),
                ('montant_journee_coutrev', models.FloatField(blank=True, db_column='montant_journee_coutRev', null=True)),
                ('montantcumul_coutrev', models.FloatField(blank=True, db_column='MontantCumul_coutRev', null=True)),
                ('pu_prix_vente', models.FloatField(blank=True, db_column='PU_prix_vente', null=True)),
                ('montant_journee_prix_vente', models.FloatField(blank=True, null=True)),
                ('montantcumul_prix_vente', models.FloatField(blank=True, db_column='MontantCumul_prix_vente', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('produit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Production',
            },
        ),
        migrations.CreateModel(
            name='Tcr',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('n_field', models.TextField(blank=True, db_column='N°', null=True)),
                ('des', models.TextField(blank=True, db_column='Désignation ', null=True)),
                ('siege', models.FloatField(blank=True, db_column='SIEGE', null=True)),
                ('kdu', models.FloatField(blank=True, db_column='KDU', null=True)),
                ('skdu', models.FloatField(blank=True, db_column='SKDU', null=True)),
                ('azdu', models.FloatField(blank=True, db_column='AZDU', null=True)),
                ('entreprise', models.FloatField(blank=True, db_column='ENTREPRISE', null=True)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TCR',
            },
        ),
        migrations.CreateModel(
            name='Trs',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('unite', models.TextField(blank=True, db_column='Unité', null=True)),
                ('ligne', models.TextField(blank=True, db_column='Ligne', null=True)),
                ('ecarts_cadences', models.BigIntegerField(blank=True, db_column='Ecarts_Cadences', null=True)),
                ('arret_plan', models.BigIntegerField(blank=True, db_column='Arret_Plan', null=True)),
                ('arret_non_plan', models.BigIntegerField(blank=True, db_column='Arret_non_Plan', null=True)),
                ('capacite_theo', models.BigIntegerField(blank=True, db_column='Capacite_Theo', null=True)),
                ('qte_prod', models.BigIntegerField(blank=True, db_column='Qte_Prod', null=True)),
                ('qte_conf', models.BigIntegerField(blank=True, db_column='Qte_Conf', null=True)),
                ('qte_rebut', models.BigIntegerField(blank=True, db_column='Qte_Rebut', null=True)),
                ('temps_ouv', models.BigIntegerField(blank=True, db_column='Temps_Ouv', null=True)),
                ('temps_fct', models.BigIntegerField(blank=True, db_column='Temps_Fct', null=True)),
                ('temps_req', models.BigIntegerField(blank=True, db_column='Temps_Req', null=True)),
                ('taux_dispo', models.FloatField(blank=True, db_column='Taux_Dispo', null=True)),
                ('temps_net', models.BigIntegerField(blank=True, db_column='Temps_Net', null=True)),
                ('taux_perf', models.FloatField(blank=True, db_column='Taux_Perf', null=True)),
                ('temps_util', models.FloatField(blank=True, db_column='Temps_Util', null=True)),
                ('taux_qualit', models.FloatField(blank=True, db_column='Taux_Qualit', null=True)),
                ('trs', models.FloatField(blank=True, db_column='TRS', null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TRS',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('unite', models.TextField(blank=True, db_column='Unité', null=True)),
                ('des', models.TextField(blank=True, db_column='Désignation', null=True)),
                ('client', models.TextField(blank=True, db_column='Client', null=True)),
                ('qte_journ', models.BigIntegerField(blank=True, db_column='Qte_Journ', null=True)),
                ('qte_cumul', models.BigIntegerField(blank=True, db_column='Qte_Cumul', null=True)),
                ('pu', models.TextField(blank=True, db_column='PU', null=True)),
                ('montant_journee', models.FloatField(blank=True, db_column='Montant_journee', null=True)),
                ('montant_cumul', models.FloatField(blank=True, db_column='Montant_cumul', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Vente',
            },
        ),
    ]
