# Generated by Django 3.2 on 2022-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcr',
            name='azdu',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='des',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='kdu',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='month',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='n_field',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='siege',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='skdu',
        ),
        migrations.RemoveField(
            model_name='tcr',
            name='year',
        ),
        migrations.AddField(
            model_name='tcr',
            name='achats_consom',
            field=models.FloatField(blank=True, db_column='Achats consommes', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='ca',
            field=models.FloatField(blank=True, db_column="Chiffre d'affaires", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='cessions_et_produits',
            field=models.BigIntegerField(blank=True, db_column='Cessions et produits', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='charge_financ',
            field=models.FloatField(blank=True, db_column='Charges financières', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='charge_inter_unit',
            field=models.BigIntegerField(blank=True, db_column='Charges inter unités', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='charge_pers',
            field=models.FloatField(blank=True, db_column='Charges de personnel', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='consom_exerc',
            field=models.FloatField(blank=True, db_column="CONSOMMATIONS DE L'EXERCICE (II)", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='consom_inter_unit',
            field=models.BigIntegerField(blank=True, db_column='Consommation inter-unités', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='dot_amort_prov_pert_val',
            field=models.FloatField(blank=True, db_column='Dotation aux amortissements, provisions et pertes de valeur ', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='elem_extraord_charge',
            field=models.BigIntegerField(blank=True, db_column='Eléments extraordinaires charges', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='elem_extraord_prod',
            field=models.BigIntegerField(blank=True, db_column='Eléments extraordinaires produits', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='exced_brut_exploit',
            field=models.FloatField(blank=True, db_column="\xa0EXCEDENT BRUT D'EXPLOITATION", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='impot_diff_res_ord',
            field=models.BigIntegerField(blank=True, db_column='Impôts différés (Variations) sur résultats ordinaires', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='impot_exig_res_ord',
            field=models.BigIntegerField(blank=True, db_column='Impôts exigibles sur résultats ordinaires', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='impot_tax_vers_ass',
            field=models.BigIntegerField(blank=True, db_column='Impôts, taxes et versements assimiles', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='other_charge_op',
            field=models.FloatField(blank=True, db_column='Autres charges opérationnelles', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='other_prod_op',
            field=models.FloatField(blank=True, db_column='Autres produits opérationnels', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='prod_exerc',
            field=models.FloatField(blank=True, db_column="PRODUCTION DE L'EXERCICE (I)", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='prod_fin',
            field=models.FloatField(blank=True, db_column='Produits financiers', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='prod_immob',
            field=models.FloatField(blank=True, db_column='Production immobilisée', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='prod_inter_unit',
            field=models.BigIntegerField(blank=True, db_column='Produits inter unités', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='repr_pert_val_prov',
            field=models.BigIntegerField(blank=True, db_column='Reprise sur pertes de valeur et provisions', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_extraord',
            field=models.BigIntegerField(blank=True, db_column='RESULTAT EXTRAORDINAIRE ', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_financ',
            field=models.FloatField(blank=True, db_column='RESULTAT FINANCIER', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_net_act_ord',
            field=models.FloatField(blank=True, db_column='RESULTAT NET DES ACTIVITES ORDINAIRES ', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_net_exerc',
            field=models.FloatField(blank=True, db_column="RESULTAT NET DE L'EXERCICE", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_op',
            field=models.FloatField(blank=True, db_column=' RESULTAT OPERATIONNEL', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='res_ord_pre_impot',
            field=models.FloatField(blank=True, db_column='RESULTAT ORDINAIRE AVANT IMPOTS (V + VI)', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='subv_expl',
            field=models.BigIntegerField(blank=True, db_column="Subventions d'exploitation", null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='tot_charge_act_ord',
            field=models.FloatField(blank=True, db_column='Total des charges des activités ordinaires', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='tot_prod_act_ord',
            field=models.FloatField(blank=True, db_column='Total des produits des activités ordinaires', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='unite',
            field=models.TextField(blank=True, db_column='Unité', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='v_ajoute',
            field=models.FloatField(blank=True, db_column='VALEUR AJOUTEE (I - II)', null=True),
        ),
        migrations.AddField(
            model_name='tcr',
            name='var_stock_fini_encours',
            field=models.FloatField(blank=True, db_column='Variation stocks produits finis et en cours', null=True),
        ),
        migrations.AlterField(
            model_name='tcr',
            name='id',
            field=models.TextField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
