# Generated by Django 3.2 on 2022-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcr',
            name='serv_ext_other_consom',
            field=models.FloatField(blank=True, db_column='Services extérieurs et Autres consommation', null=True),
        ),
    ]
