# Generated by Django 3.2 on 2022-02-22 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_tcr_serv_ext_other_consom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tab', models.TextField(blank=True, null=True)),
                ('line_id', models.TextField(blank=True, null=True)),
                ('op', models.TextField(blank=True, choices=[(1, 'CREATE'), (2, 'EDIT'), (3, 'DELETE')], null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
