# Generated by Django 3.2 on 2022-02-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
