# Generated by Django 3.2 on 2022-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='op',
            field=models.TextField(blank=True, choices=[(1, 'AJOUT'), (2, 'MODIFICATION'), (3, 'SUPPRESSION')], null=True),
        ),
        migrations.AlterField(
            model_name='tcr',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
