# Generated by Django 3.2 on 2022-03-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_objectifcapaciteproduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectifCapaciteProduction',
        ),
    ]
