# Generated by Django 3.2 on 2022-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_production_capacite_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_capacite_imp',
            name='abs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='autres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='chg_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='lvg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='manque_prog',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='panne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='pause_eat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='prep_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='reglages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
