# Generated by Django 3.2 on 2022-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220417_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash_impression',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
