# Generated by Django 3.2 on 2022-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_flash_impression_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_capacite_imp',
            name='nb_feuill_post_arret',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='production_capacite_imp',
            name='nb_feuill_pre_arret',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
